FROM golang:1.21 as base

FROM base as dev

WORKDIR /app/api
# RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
RUN go install github.com/cosmtrek/air@latest
ENV CGO_ENABLED=0

COPY go*.* ./
RUN go mod download && go mod tidy && go mod verify && go mod vendor

COPY . .

CMD ["tail", "-f", "/dev/null"]
