version: "3.9"
services:
  go-todo-api:
    container_name: go-todo-api
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app/api
    depends_on:
      - go-todo-postgres
    env_file:
      - .env
    ports:
    - ${GOTODO_API_HTTP_PORT:-4000}:${GOTODO_API_HTTP_EXPOSE_PORT:-4000}
    command: tail -f /dev/null
    networks:
      - todo-backend-network

  go-todo-postgres:
    container_name: go-todo-postgres
    image: ${GOTODO_POSTGRES_IMAGE:-postgres:14.5}
    environment:
      POSTGRES_DB: ${GOTODO_POSTGRES_DB:-pg-db}
      POSTGRES_USER: ${GOTODO_POSTGRES_USER:-pg-user}
      POSTGRES_PASSWORD: ${GOTODO_POSTGRES_PASSWORD:-pg-password}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./psql:/var/lib/postgresql/data
    ports:
      - 5433:${GOTODO_POSTGRES_PORT:-5432}
    env_file:
      - .env
    networks:
      - todo-backend-network

networks:
  todo-backend-network:
    driver: bridge