version: "3.9"
services:
  go-todo-api:
    container_name: go-todo-api
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app/api
    ports:
    - "4000:3000"
    networks:
      - todo-backend-network

networks:
  todo-backend-network:
    driver: bridge